export default {
  filter: "Filter",
  search_for: "Search for",
  type_a_number: "Type a number",
  type_some_text: "Type some text",
  contains: "Contains",
  and: "And",
  or: "Or",
  lessThan: "Less Than",
  greaterThan: "Greater Than",
  add: "Add",
  new: "New",
  remove: "Remove",
  condition: "Condition",
  value: "Value",
  connection: "Connection",
  required: "Value is required",
  system_actions: "SystemActions",
  system_select: "SystemSelect",
  manage_columns: "Manage Columns",
  manage: "Manage",
  hide: "Hide",
  pin: "Pin",
  apply: "Apply",
  reset: "Reset",
};
